### ISSUE TITLE
import lib

### ISSUE THREAD

**Issue by vivi3n** [dl4to/dl4to#3]
Dear dl4to team, 

Sorry, I'm certainly an idiot, but I can't find the way to build the SELTODataset. It seems to have built itself a few times (I found a folder with the dataset but not properly finished). Above all, beyond the error, even with this folder, it returns me when checking that the folder doesn't exist. 

pytorch 2.3.0+cu118
I'm on windows11

>>> dataset.info() 
>>> File "<stdin>", line 1, in <module>

I'm pretty bad at coding, so I'm trying to figure it out, but maybe I'm not making the right choices. 

-------------- the error
Found 0 files.
Downloading disc_simple_train...
Done!
Extracting disc_simple_train...
Done!
Generating dataset...
  0%|          | 0/1509 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 883, in __init__
    super().__init__(root=root,
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 711, in __init__
    self._generate_dataset(
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 760, in _generate_dataset
    csv_converter(self.pt_dir_path)
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 177, in __call__
    sample = self[i]
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 85, in __getitem__
    F, Ω_dirichlet, Ω_design = self._get_forces_boundary_conditions_and_design_space(data, shape, voxels)
  File "C:\python\lib\site-packages\dl4to\datasets.py", line 148, in _get_forces_boundary_conditions_and_design_space
    Ω_design[:, voxels[0], voxels[1], voxels[2]] = torch.from_numpy(data['design_space'].values.astype(int))
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

Best. 
Thanks for your work.

**Comment by dl4to** [comment]
Sorry for the very delayed answer, your question somehow slipped through!
I unfortunately cannot reproduce your issue, for me the downloading works. I would propose to properly delete the old folders from the dataset and download it again. Maybe the download does not work if a folder with the name of the dataset already exists.

Best regards,
David
